<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 */

$translate = $this->plugin('translate');
$this->headLink()->prependStylesheet($this->assetUrl('css/custom-ontology.css', 'CustomOntology'));
?>

<h3><?= $translate('List of custom ontologies') ?></h3>
<?php if (empty($ontologies)): ?>
<p><?= $translate('There are no custom ontology.') ?></p>
<?php else: ?>
<ul>
<?php foreach ($ontologies as $ontology): ?>
    <li>
        <dt><?= $ontology->label() ?></dt>
        <dd><?= sprintf($translate('%1$s (%2$shuman%4$s | %3$sturtle%4$s) [recommended prefix: %5$s]'),
                $ontology->namespaceUri(),
                '<a href="' . $this->url('ns/prefix', ['prefix' => $ontology->prefix()], ['query' => ['format' => 'html']]) . '">',
                '<a href="' . $ontology->namespaceUri() . '">',
                '</a>',
                $ontology->prefix()
            )
        ?></dd>
    </li>
<?php endforeach; ?>
</ul>
<?php endif;
