<?php
/** @var \Laminas\View\Renderer\PhpRenderer $this */
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headLink()->prependStylesheet($this->assetUrl('css/custom-ontology.css', 'CustomOntology'));
$this->headLink()->prependStylesheet($this->assetUrl('vendor/tablesaw/tablesaw.stackonly.css', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/tablesaw/tablesaw.stackonly.jquery.js', 'Omeka'), 'text/javascript', ['defer' => 'defer']);
?>
<h3><?php echo $translate($ontology->label()); ?></h3>

<ul>
    <li><?php echo sprintf($translate('Namespace uri: %s'), $ontology->namespaceUri()); ?></li>
    <li><?php echo sprintf($translate('Recommended prefix: %s'), $ontology->prefix()); ?></li>
    <li><?php echo sprintf($translate('As %s'), $this->hyperlink($translate('turtle'), $ontology->namespaceUri())); ?></li>
</ul>
<?php if ($comment = $ontology->comment()): ?>
<p><?php echo $translate($comment); ?>
<?php endif; ?>

<h4><?php echo $translate('Resource classes'); ?></h4>
<?php $resourceClasses = $ontology->resourceClasses(); ?>
<?php if (empty($resourceClasses)): ?>
<p><?php echo $translate('There are no resource classes.'); ?></p>
<?php else: ?>
<table class="tablesaw tablesaw-stack" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $translate('Label'); ?></th>
            <th><?php echo $translate('Term'); ?></th>
            <th><?php echo $translate('Comment'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($resourceClasses as $resourceClass): ?>
        <tr>
            <td>
                <span class="resource-class-label">
                    <?php echo $escape($translate($resourceClass->label())); ?>
                </span>
            </td>
            <td><?php echo $escape($translate($resourceClass->term())); ?></td>
            <td><?php echo $escape($translate($resourceClass->comment())); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>

<h4><?php echo $translate('Properties'); ?></h4>
<?php $properties = $ontology->properties(); ?>
<?php if (empty($properties)): ?>
<p><?php echo $translate('There are no properties.'); ?></p>
<?php else: ?>
<table class="tablesaw tablesaw-stack" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $translate('Label'); ?></th>
            <th><?php echo $translate('Term'); ?></th>
            <th><?php echo $translate('Comment'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($properties as $property): ?>
        <tr>
            <td>
                <span class="resource-class-label">
                    <?php echo $escape($translate($property->label())); ?>
                </span>
            </td>
            <td><?php echo $escape($translate($property->term())); ?></td>
            <td><?php echo $escape($translate($property->comment())); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
