<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\VocabularyRepresentation $ontology
 */

$plugins = $this->getHelperPluginManager();
$escape = $this->plugin('escapeHtml');
$assetUrl = $this->plugin('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$this->headLink()
    ->prependStylesheet($assetUrl('css/custom-ontology.css', 'CustomOntology'))
    ->prependStylesheet($assetUrl('vendor/tablesaw/tablesaw.stackonly.css', 'Omeka'));
$this->headScript()
    ->prependFile($assetUrl('vendor/tablesaw/tablesaw.stackonly.jquery.js', 'Omeka'), 'text/javascript', ['defer' => 'defer']);
?>

<h3><?= $translate($ontology->label()) ?></h3>

<ul>
    <li class="vocabulary-uri"><?= sprintf($translate('Namespace uri: %s'), $ontology->namespaceUri()) ?></li>
    <li class="vocabulary-prefix"><?= sprintf($translate('Recommended prefix: %s'), '<strong>' . $ontology->prefix() . '</strong>') ?></li>
    <li class="vocabulary-links"><?= sprintf($translate('As %s'), $hyperlink($translate('turtle'), $ontology->namespaceUri())) ?></li>
</ul>
<?php if ($comment = $ontology->comment()): ?>
<p><?= $translate($comment) ?>
<?php endif; ?>

<h4><?= $translate('Classes') ?></h4>
<?php $resourceClasses = $ontology->resourceClasses(); ?>
<?php if (!count($resourceClasses)): ?>
<p><?= $translate('There are no classes.') ?></p>
<?php else: ?>
<table class="tablesaw tablesaw-stack" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?= $translate('Label') ?></th>
            <th><?= $translate('Term') ?></th>
            <th><?= $translate('Comment');?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($resourceClasses as $resourceClass): ?>
        <tr>
            <td>
                <span class="resource-class-label">
                    <?= $escape($translate($resourceClass->label())) ?>
                </span>
            </td>
            <td><?= $escape($translate($resourceClass->term())) ?></td>
            <td><?= $escape($translate($resourceClass->comment())) ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>

<h4><?= $translate('Properties') ?></h4>
<?php $properties = $ontology->properties(); ?>
<?php if (!count($properties)): ?>
<p><?= $translate('There are no properties.') ?></p>
<?php else: ?>
<table class="tablesaw tablesaw-stack" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?= $translate('Label') ?></th>
            <th><?= $translate('Term') ?></th>
            <th><?= $translate('Comment') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($properties as $property): ?>
        <tr>
            <td>
                <span class="resource-class-label">
                    <?= $escape($translate($property->label())) ?>
                </span>
            </td>
            <td><?= $escape($translate($property->term())) ?></td>
            <td><?= $escape($translate($property->comment())) ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
